[package]
authors = ["Sebastian Wicki <swicki@student.ethz.ch>"]
name = "timely-query"
version = "0.1.0"

[[bin]]
name = "coordinator"
path = "src/bin/coordinator.rs"

[[bin]]
name = "executor"
path = "src/bin/executor.rs"

[[bin]]
name = "timely-submit"
path = "src/bin/timely-submit.rs"

[dependencies]
abomonation = "^0.4.2"
byteorder = "0.5.3"
env_logger = "0.3"
log = "0.3"
rand = "0.3.14"

[dependencies.futures]
git = "https://github.com/alexcrichton/futures-rs"

[dependencies.timely]
git = "https://github.com/frankmcsherry/timely-dataflow"
