[workspace]
members = [
    "src/strymon_communication",
    "src/strymon_runtime",
    "src/strymon_cli"
]

[replace."timely_communication:0.1.8"]
git = "ssh://git@gitlab.inf.ethz.ch/PROJECT-STRYMON/timely-dataflow.git"
branch = "0.1.7"
