[package]
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]
name = "strymon_cli"
version = "0.1.0"

[[bin]]
name = "strymon"
path = "src/main.rs"

[dependencies]
clap = "~2.26.2"
error-chain = "0.11.0"
