[package]
authors = ["Sebastian Wicki <gandro@gmx.net>"]
name = "networking"
version = "0.1.0"

[dependencies]
abomonation = "0.4.4"
log = "0.3.6"
mio = "0.6.0"
slab = "0.3.0"

[replace]

[replace."mio:0.6.0"]
git = "https://github.com/carllerche/mio"
rev = "9f17b70"
