[package]
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]
name = "strymon-runtime"
version = "0.1.0"

[[bin]]
name = "strymon"
path = "src/bin/main.rs"

[dependencies]
env_logger = "0.4"
futures = "0.1"
tokio-core = "0.1"
log = "0.3"
rand = "0.3.14"
timely = "0.2.0"
timely_communication = "0.1.5"
serde = "1.0"
serde_derive = "1.0"
abomonation = "0.4.5"
abomonation_derive = "0.1.2"
clap = "~2.26.2"
error-chain = "0.11.0"

[dependencies.strymon_communication]
path = "../strymon_communication/"
