[package]
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]
name = "timely-system"
version = "0.1.0"

[[bin]]
name = "coordinator"
path = "src/bin/coordinator.rs"

[[bin]]
name = "executor"
path = "src/bin/executor.rs"

[[bin]]
name = "submit"
path = "src/bin/submit.rs"

[[bin]]
name = "status"
path = "src/bin/status.rs"

[dependencies]
env_logger = "0.3"
futures = "0.1"
tokio-core = "0.1"
getopts = "0.2.14"
log = "0.3"
rand = "0.3.14"
timely = "0.2.0"
timely_communication = "0.1.5"
serde = "1.0"
serde_derive = "1.0"
abomonation = "0.4.5"
abomonation_derive = "0.1.2"

[dependencies.strymon_communication]
path = "../strymon_communication/"
